### ISSUE TITLE
guidance on relevant images

### ISSUE THREAD

**Issue by GochoMugo** [hypriot/rpi-influxdb#1]
I have just started using this image. And I like it. Good work. :+1:

Do you have any plans on adding images for the complete TICK stack i.e. Telegraf, Chronograf and Kapacitor? The Dockerfile can be re-used mostly, to install the other executables.

I would be glad to help, where I can, to allow consolidation of efforts towards supporting docker images on ARM.

**Comment by StefanScherer** [comment]
Thanks for offering help. You could create a new repo and adjust it for the next service. Then ping me to setup the corresponding hypriot repo and Travis build.

**Comment by StefanScherer** [comment]
Closing this. BTW: The official influxdb image now supports ARM:

```
$ docker run --rm mplatform/mquery influxdb
Image: influxdb
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - linux/arm64/v8
```
